"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const authController_1 = require("../controllers/authController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const validateMiddleware_1 = require("../middleware/validateMiddleware");
const authValidator_1 = require("../validators/authValidator");
const router = express_1.default.Router();
router.post('/register', (0, validateMiddleware_1.validateRequest)(authValidator_1.registerSchema), authController_1.registerUser);
router.post('/login', (0, validateMiddleware_1.validateRequest)(authValidator_1.loginSchema), authController_1.loginUser);
router.post('/password/forgot', (0, validateMiddleware_1.validateRequest)(authValidator_1.forgotPasswordSchema), authController_1.requestPasswordResetCode);
router.post('/password/reset', (0, validateMiddleware_1.validateRequest)(authValidator_1.resetPasswordSchema), authController_1.resetPasswordWithCode);
router.get('/oauth/google', authController_1.startGoogleOAuth);
router.get('/oauth/google/callback', authController_1.googleOAuthCallback);
router.get('/oauth/github', authController_1.startGitHubOAuth);
router.get('/oauth/github/callback', authController_1.githubOAuthCallback);
router.post('/logout', authController_1.logoutUser);
router.get('/profile', authMiddleware_1.protect, authController_1.getUserProfile);
router.put('/profile', authMiddleware_1.protect, (0, validateMiddleware_1.validateRequest)(authValidator_1.updateProfileSettingsSchema), authController_1.updateUserProfile);
router.put('/password/change', authMiddleware_1.protect, (0, validateMiddleware_1.validateRequest)(authValidator_1.changePasswordSchema), authController_1.changeUserPassword);
router.put('/email/change', authMiddleware_1.protect, (0, validateMiddleware_1.validateRequest)(authValidator_1.changeEmailSchema), authController_1.changeUserEmail);
router.put('/preferences/notifications', authMiddleware_1.protect, (0, validateMiddleware_1.validateRequest)(authValidator_1.updateNotificationPreferencesSchema), authController_1.updateNotificationPreferences);
router.put('/preferences/appearance', authMiddleware_1.protect, (0, validateMiddleware_1.validateRequest)(authValidator_1.updateAppearancePreferenceSchema), authController_1.updateAppearancePreferences);
router.get('/favorites/courses', authMiddleware_1.protect, authController_1.getFavoriteCourses);
router.post('/favorites/courses/:courseId', authMiddleware_1.protect, authController_1.addFavoriteCourse);
router.delete('/favorites/courses/:courseId', authMiddleware_1.protect, authController_1.removeFavoriteCourse);
router.get('/favorites/resources', authMiddleware_1.protect, authController_1.getFavoriteResources);
router.post('/favorites/resources/:resourceId', authMiddleware_1.protect, authController_1.addFavoriteResource);
router.delete('/favorites/resources/:resourceId', authMiddleware_1.protect, authController_1.removeFavoriteResource);
router.get('/users', authMiddleware_1.protect, (0, authMiddleware_1.authorizeRoles)('admin'), authController_1.getUsers);
router.put('/users/:id/role', authMiddleware_1.protect, (0, authMiddleware_1.authorizeRoles)('admin'), authController_1.updateUserRole);
router.put('/users/:id/status', authMiddleware_1.protect, (0, authMiddleware_1.authorizeRoles)('admin'), authController_1.updateUserStatus);
router.delete('/users/:id', authMiddleware_1.protect, (0, authMiddleware_1.authorizeRoles)('admin'), authController_1.softDeleteUser);
router.get('/activity-logs', authMiddleware_1.protect, (0, authMiddleware_1.authorizeRoles)('admin'), authController_1.getActivityLogs);
exports.default = router;
//# sourceMappingURL=authRoutes.js.map